# Generated by Django 3.0.4 on 2020-03-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200328_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
